title = "Gitleaks config"
[[rules]]
  description = "Potential AWS secret key"
  regex = '''AKIA[0-9A-Z]{16}'''
  tags = ["key", "aws"]
[[rules]]
  description = "Generic API key"
  regex = '''[A-Za-z0-9]{32,}'''
  tags = ["key", "generic"]
