#!/bin/bash

# ============================================================================
# UNIFIED REPORTING ENGINE - PILGRIMS v17.0
# ============================================================================

# Generate unified report across multiple modules
generate_unified_report() {
    local output_dir=$1
    local modules=("${@:2}")
    
    print_phase_header "REPORT" "📊 GENERATING UNIFIED REPORT"
    
    local report_file="$output_dir/UNIFIED_REPORT_$(get_timestamp).md"
    
    cat > "$report_file" << EOF
# 🏴‍☠️ PILGRIMS Unified Security Report

**Generated:** $(date)  
**Modules Scanned:** ${modules[*]}  
**Scanner Version:** v17.0 - Ultimate Edition

---

## 📊 Executive Summary

EOF
    
    local total_critical=0
    local total_high=0
    local total_medium=0
    local total_low=0
    
    # Collect stats from each module
    for module in "${modules[@]}"; do
        local module_dir="$SCRIPT_DIR/modules/module-$module/reports"
        local latest_scan=$(ls -dt "$module_dir"/* 2>/dev/null | head -1)
        
        if [ -n "$latest_scan" ]; then
            local critical=$(count_findings "$latest_scan" "CRITICAL")
            local high=$(count_findings "$latest_scan" "HIGH")
            local medium=$(count_findings "$latest_scan" "MEDIUM")
            local low=$(count_findings "$latest_scan" "LOW")
            
            total_critical=$((total_critical + critical))
            total_high=$((total_high + high))
            total_medium=$((total_medium + medium))
            total_low=$((total_low + low))
            
            cat >> "$report_file" << EOF
### 🔧 Module: $module

| Severity | Count |
|----------|-------|
| 🔴 Critical | $critical |
| 🟠 High | $high |
| 🟡 Medium | $medium |
| 🟢 Low | $low |

EOF
        fi
    done
    
    # Overall summary
    local total=$((total_critical + total_high + total_medium + total_low))
    local risk_score=$((total_critical * 40 + total_high * 25 + total_medium * 10 + total_low * 3))
    [ $risk_score -gt 100 ] && risk_score=100
    
    cat >> "$report_file" << EOF
---

## 🎯 Overall Statistics

| Metric | Value |
|--------|-------|
| **Total Findings** | $total |
| 🔴 Critical | $total_critical |
| 🟠 High | $total_high |
| 🟡 Medium | $total_medium |
| 🟢 Low | $total_low |
| **Risk Score** | $risk_score / 100 |

---

## 📋 Detailed Findings

EOF
    
    # Add detailed findings from each module
    for module in "${modules[@]}"; do
        local module_dir="$SCRIPT_DIR/modules/module-$module/reports"
        local latest_scan=$(ls -dt "$module_dir"/* 2>/dev/null | head -1)
        
        if [ -n "$latest_scan" ]; then
            cat >> "$report_file" << EOF
### 🔧 $module

\`\`\`
$(find "$latest_scan" -name "*.txt" -exec grep -hE "\[CRITICAL\]|\[HIGH\]" {} + 2>/dev/null | head -20)
\`\`\`

EOF
        fi
    done
    
    # Recommendations
    cat >> "$report_file" << EOF
---

## 🛡️ Recommendations

### Immediate Actions (Critical)
$(if [ $total_critical -gt 0 ]; then
    echo "- [ ] Address all critical vulnerabilities immediately"
    echo "- [ ] Review attack paths and prioritize remediation"
else
    echo "- ✅ No critical vulnerabilities found"
fi)

### Short-term Actions (High)
$(if [ $total_high -gt 0 ]; then
    echo "- [ ] Schedule remediation for high-severity findings"
    echo "- [ ] Review security configurations"
else
    echo "- ✅ No high-severity vulnerabilities found"
fi)

### Long-term Actions
- [ ] Implement regular security assessments
- [ ] Conduct security awareness training
- [ ] Establish incident response procedures
- [ ] Implement continuous monitoring

---

## 📎 Appendix

### Scan Details
- **Scanner:** PILGRIMS v17.0 - Hybrid Edition
- **Architecture:** Modular with unified reporting
- **Modules Used:** ${modules[*]}
- **Generated:** $(date)

---

*Report generated by PILGRIMS - Navigating the Digital Seas of Cybersecurity*
EOF
    
    print_success "Unified report: $report_file"
}

# Generate HTML unified report
generate_unified_html() {
    local output_dir=$1
    shift
    local modules=("$@")
    
    local html_file="$output_dir/UNIFIED_REPORT_$(get_timestamp).html"
    
    cat > "$html_file" << 'EOF'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PILGRIMS Unified Security Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { 
            font-family: 'Segoe UI', sans-serif; 
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
            padding: 20px; 
        }
        .container { max-width: 1200px; margin: 0 auto; }
        .header { 
            background: rgba(255,255,255,0.95); 
            padding: 40px; 
            border-radius: 15px; 
            text-align: center; 
            margin-bottom: 30px; 
        }
        .header h1 { 
            font-size: 3em; 
            background: linear-gradient(135deg, #667eea, #764ba2); 
            -webkit-background-clip: text; 
            -webkit-text-fill-color: transparent; 
        }
        .card { 
            background: white; 
            padding: 30px; 
            border-radius: 15px; 
            margin-bottom: 20px; 
            box-shadow: 0 5px 20px rgba(0,0,0,0.1); 
        }
        .card h2 { 
            color: #667eea; 
            border-bottom: 3px solid #667eea; 
            padding-bottom: 10px; 
            margin-bottom: 20px; 
        }
        .metric { 
            display: inline-block; 
            background: linear-gradient(135deg, #667eea, #764ba2); 
            color: white; 
            padding: 20px 30px; 
            border-radius: 10px; 
            margin: 10px; 
            text-align: center; 
            min-width: 180px; 
        }
        .metric .value { font-size: 2.5em; font-weight: bold; }
        .metric .label { font-size: 0.9em; opacity: 0.9; }
        .finding { 
            padding: 15px; 
            border-left: 5px solid; 
            margin: 10px 0; 
            border-radius: 5px; 
        }
        .critical { background: #ffebee; border-color: #f44336; }
        .high { background: #fff3e0; border-color: #ff9800; }
        .medium { background: #fffde7; border-color: #ffeb3b; }
        .low { background: #e8f5e9; border-color: #4caf50; }
        table { width: 100%; border-collapse: collapse; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background: #f5f5f5; color: #667eea; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🏴‍☠️ PILGRIMS Unified Report</h1>
            <p>Multi-Domain Security Assessment</p>
        </div>
        
        <div class="card">
            <h2>📊 Executive Summary</h2>
            <div style="text-align: center;">
EOF
    
    # Add metrics for each module
    for module in "${modules[@]}"; do
        local module_dir="$SCRIPT_DIR/modules/module-$module/reports"
        local latest_scan=$(ls -dt "$module_dir"/* 2>/dev/null | head -1)
        
        if [ -n "$latest_scan" ]; then
            local findings=$(get_total_findings "$latest_scan")
            cat >> "$html_file" << EOF
                <div class="metric">
                    <div class="value">$findings</div>
                    <div class="label">$module</div>
                </div>
EOF
        fi
    done
    
    cat >> "$html_file" << 'EOF'
            </div>
        </div>
        
        <div class="card">
            <h2>🛡️ Recommendations</h2>
            <ul style="margin-left: 30px; line-height: 2;">
                <li>Address critical vulnerabilities immediately</li>
                <li>Implement security best practices across all domains</li>
                <li>Conduct regular security assessments</li>
                <li>Establish incident response procedures</li>
            </ul>
        </div>
        
        <div style="text-align: center; padding: 30px; color: white;">
            <p>🏴‍☠️ PILGRIMS v17.0 - Hybrid Edition</p>
        </div>
    </div>
</body>
</html>
EOF
    
    print_success "HTML report: $html_file"
}
